#!/usr/bin/env bash

# Inicio das funções
################################################################################
# Função para mostrar mensagem de erro
_MSG_ERRO_INFO() { clear ; whiptail --title "Erro" --msgbox "$1" 0 0 ; exit 20 ; }

################################################################################

# Função para mostrar mensagem
_MSG_INFO(){ clear ; whiptail --title "Atenção" --msgbox "$1" 0 0 ; }

################################################################################

# Função para mostrar mensagem de sair
_MSG_SAIR(){ clear ; whiptail --title "Aviso" --msgbox "$1" 0 0 ; exit 30 ; }

# Função para verificar se o script está com privilegios de root, Caso não estiver finaliza o programa.
# Pacote necessário whiptail para mensagem na tela.
_VERIFICAR_ROOT()
{
  which whiptail > /dev/null || yum install -y newt
  [ "$EUID" -eq 0 ] || _MSG_ERRO_INFO "Necessita permissão de root"
}

################################################################################
# Função para verificar o sistema operacional
_VERIFICAR_OS() { grep -oq "rocky" /etc/os-release || _MSG_ERRO_INFO "Sistema operacional não homologado, usar Centos 8 e/ou Rocky Linux 8" ; }

# Função para verificar acesso a internert para baixar os pacotes necessários
_VERIFICAR_INTERNET(){ ping -c 2 -w 5 "kernel.org" > /dev/null || _MSG_ERRO_INFO "Acesso a internet não está disponível" ; }

################################################################################
# Função para testar ip fornecido, utiliza programa auxiliar ipcalc
_TESTA_IP()
{
  which ipcalc 1> /dev/null || yum -y install ipcalc 1> /dev/null
  IPCALC=$(which ipcalc) 1> /dev/null
  "$IPCALC" -c "$1" || _MSG_ERRO_INFO "Favor verificar o Endereço IP informado"
}

################################################################################
# Função para validar ip reverso para criação do dns no DC
_REVERSO()
{
  IP=$(grep -i "ip" /tmp/samba.db | cut -d "=" -f 2)
  MSK=$(grep -i "mascara" /tmp/samba.db | cut -d "=" -f 2)
  ARPA="in-addr.arpa"
  RES=$(ipcalc -p "${IP}/${MSK}")

# Máscara classe C
  if [[ ${RES##*=} -ge "17" ]] && [[ ${RES##*=} -le "24" ]]
    then
      IP1=$(cut -d"." -f 1 <<< "${IP}")
      IP2=$(cut -d"." -f 2 <<< "${IP}")
      IP3=$(cut -d"." -f 3 <<< "${IP}")
      REV=("${IP3}"\."${IP2}"\."${IP1}"\."${ARPA}")

# Máscara classe B
 elif [[ ${RES##*=} -ge "9" ]] && [[ ${RES##*=} -le "16" ]]
    then
      IP1=$(cut -d"." -f 1 <<< "${IP}")
      IP2=$(cut -d"." -f 2 <<< "${IP}")
      REV=("${IP2}"\."${IP1}"\."${ARPA}")

# Máscara classe A
  else [[ ${RES##*=} -ge "1" ]] && [[ ${RES##*=} -le "8" ]]
      IP1=$(cut -d"." -f 1 <<< "${IP}")
      REV=("${IP1}"\."${ARPA}")

  fi
  echo "${REV[@]}"
}

################################################################################
# Função para escolher interface de rede caso exista mais de uma
# Gerado uma lista com os nomes das interfaces de rede, caso existir mais de um.
_INTERFACE()
{
  TMP=$(ip -o -4 route show to default | awk '{print $5}' | uniq)
  TM=$(ip -o -4 route show to default | awk '{print $5}' | uniq | tail -n 1)

  arr=()
  i=0
  for ip in $TMP
  do
    #echo "${ip[i]}"
    arr=("${ip[i]}" "${arr[@]}")
  done

  whiptail_args=(
    --title "Escolha a interface de rede"
    --radiolist "Interface disponivel:"
    10 80 "${#arr[@]}"  # note the use of ${#arrayname[@]} to get count of entries
  )

  i=0
  for db in "${arr[@]}"; do
    whiptail_args+=( "$((++i))" "$db" )
    if [[ $db = "$TM" ]]; then    # only RHS needs quoting in [[ ]]
      whiptail_args+=( "on" )
    else
      whiptail_args+=( "off" )
    fi
  done

  indice=$(whiptail "${whiptail_args[@]}" 3>&1 1>&2 2>&3)
  # echo "${arr[${indice}-1]}"
}

################################################################################
# Função para escolher ip
# Gerado uma lista com os nomes dos endereços ips, caso existir mais de um.
_IP()
{
  TMP=$(ip a | grep -E "inet[[:space:]]" |grep -v 127 | awk '{print $2}')
  TM=$(ip a  | grep -E "inet[[:space:]]" |grep -v 127 | awk '{print $2}' | head -n 1)

  arr=()
  i=0
  for ip in $TMP
    do
    #echo "${ip[i]}"
    arr=("${ip[i]}" "${arr[@]}")
    done

  whiptail_args=(
  --title "Escolha endereco de rede"
  --radiolist "Endereco disponivel:"
    10 80 "${#arr[@]}")

  i=0
  for db in "${arr[@]}"; do
    whiptail_args+=( "$((++i))" "$db" )
    if [[ $db = "$TM" ]]; then    # only RHS needs quoting in [[ ]]
      whiptail_args+=( "on" )
    else
      whiptail_args+=( "off" )
    fi
  done

  indice=$(whiptail "${whiptail_args[@]}" 3>&1 1>&2 2>&3)
  #whiptail_retval=$?
  #declare -p indice whiptail_retval
  #echo "Interface"
  echo "${arr[${indice}-1]}"
}

_VALIDAR_SENHA() {
  senha="$1"
  tamanho_minimo=8

  # Verificar o comprimento da senha
  [[ "${#senha}" -lt "$tamanho_minimo" ]] && _MSG_ERRO_INFO "Tamanho da senha informado é menor que 8 caracteres"

  # Verificar a complexidade da senha usando expressões regulares
  if ! echo "$senha" | grep -E '.*[A-Z].*' \
                     | grep -E '.*[a-z].*' \
                     | grep -E '.*[0-9].*' \
                     | grep -E '.*[@.!$%&*?<>+=_-].*'; then

MSG_COMPLEXIDADE="Senha não atende aos critérios de complexidade:
Necessário pelo menos um de cada item:
  - Letra maiúscula
  - Letra minúscula
  - Dígito numérico
  - Caractere especial
Exemplos: 'Teste@123', 'P@\$\$word.1'
"
_MSG_ERRO_INFO "$MSG_COMPLEXIDADE"

  fi
}

# Exemplo de uso:
# testa_senha "MinhaSenha123!"

#############################################################################################################################
# Função _CONFIGURAR -> Descrição:
# Função para instalação de pacotes necessários para o funcionamento do samba4
# Após a execução é criado um arquivo na pasta /tmp.
# Caso o arquivo exista o script é finalizado, necessário remover arquivo para liberar execução.
# Realizado download da versão 4.15.1 e compilação 

_CONFIGURAR()
{
  clear
  #Realizar testes antes de iniciar o script
  _VERIFICAR_ROOT
  _VERIFICAR_OS
  _VERIFICAR_INTERNET
  
  # Variáveis
  CONTROLE='/tmp/controle_configurar.txt'
  OS_RELEASE=$(grep -i platform /etc/os-release | grep -o "[0-9]")
  SAMBA_INIT="/opt"
  SAMBA_PATH="/usr/local/samba"

  [[ -f $CONTROLE ]] && _MSG_ERRO_INFO "Script já executado, favor remover o arquivo para contiunuar $CONTROLE"

  # Desabilitar SELINUX
  SELINUX_CONF=$(find /etc/ -type f -iname config | grep selinux)
  cp "$SELINUX_CONF"{,.bak}
  sed -i 's/^SELINUX=.*/SELINUX=disabled/g' "$SELINUX_CONF"
  setenforce 0

  # Liberar portas de funciomanento do Samba
  FIREWALL_CONF=$(find /etc/ -iname firewalld.conf)
  firewall-cmd --add-service={dns,ldap,ldaps,kerberos} --permanent
  firewall-cmd --add-port={389/udp,135/tcp,135/udp,138/udp,138/tcp,137/tcp,137/udp,139/udp,139/tcp,445/tcp,445/udp,3268/udp,3268/tcp,3269/tcp,3269/udp,49152/tcp,49153/tcp} --permanent
  
  sed -i 's/^AllowZoneDrifting=.*/AllowZoneDrifting=no/' "$FIREWALL_CONF"
  firewall-cmd --reload

  # Para desabilitar o firewall descamentar a linha abaixo
  # systemctl stop firewalld && systemctl disable firewalld

  #Atualizar sistema
  yum -y update && yum -y upgrade

  #Instalar repositorio EPEL e ferramentas de desenvolvimento e pacotes úteis
  yum install tar vim ipcalc net-tools wget bash-completion chrony bind-utils bind expect yum-utils krb5-workstation rsyslog -y
  
  # Baixar Samba
  wget https://download.samba.org/pub/samba/samba-latest.tar.gz || _MSG_ERRO_INFO "Erro ao baixar arquivo"
  tar zxvf samba-latest.tar.gz -C "$SAMBA_INIT" || _MSG_ERRO_INFO "Erro ao descompactar arquivo"
  
  #Pacotes necessários ajustar mensagem Whiptail #####################
  [[ "$OS_RELEASE" -eq 8 ]] || _MSG_ERRO_INFO "Versão homologada para Rocky Linux 8"

  SAMBA_BOOTSTRAP=$(find $SAMBA_INIT -iname bootstrap.sh | grep centos"$OS_RELEASE")
  bash "$SAMBA_BOOTSTRAP" || _MSG_ERRO_INFO "Erro ao executar arquivo de bootstrap"

  SAMBA_VERSAO=$(find /opt/ -maxdepth 1 -type d | grep "samba-[0-9]*")
  cd "$SAMBA_VERSAO" || _MSG_ERRO_INFO "Erro ao acessar pasta $SAMBA_VERSAO"

  #Compilando Samba4 Versão homologada para a instalação
  # Flags de compilação
  
  CFLAGS="-I/usr/include/tirpc" ./configure -j "$(nproc)" \
  --enable-coverage --disable-cups                        \
  --with-systemd --systemd-install-services               \
  --with-systemddir=/usr/lib/systemd/system               \
  --prefix="$SAMBA_PATH"                                  \
  --with-pammodulesdir=/usr/lib64/security                \
  --sysconfdir="$SAMBA_PATH"/conf
    
  make -j "$(nproc)" || _MSG_ERRO_INFO "Erro ao executar o make"
  make install       || _MSG_ERRO_INFO "Erro ao executar a instalação"

  find "$SAMBA_PATH"/lib -type d > /etc/ld.so.conf.d/samba4.conf
  echo "$SAMBA_PATH"/lib64      >> /etc/ld.so.conf.d/samba4.conf
  ldconfig

  echo export PATH="$SAMBA_PATH"/bin:"$SAMBA_PATH"/sbin:"${PATH}" >> /etc/profile
  echo "exclude=samba*" >> /etc/yum.conf
  
  # Instala chrony e atualiza a hora
  CHRONY_CONF=$(find /etc/ -type f -iname chrony.conf)
  cp "$CHRONY_CONF"{,.bkp}
  sed -i 's/^pool.*/server\ a.ntp.br\ iburst/' "$CHRONY_CONF" 
  sed -i '4s/^/server\ b.ntp.br\ iburst\n/'    "$CHRONY_CONF"
  sed -i 's/^#allow.*/allow\ 0.0.0.0\/0/'      "$CHRONY_CONF"
  timedatectl set-timezone America/Sao_Paulo

  #Inicializando chronyd e habilitando serviço
  systemctl enable chronyd --now 1> /dev/null

  # Gravando arquivo de controle
  echo "Configuracao realizada, função executada foi _CONFIGURAR" | tee > $CONTROLE

}
# Fim

################################################################################
_CONF_SAMBA()
{
  _VERIFICAR_ROOT
  _VERIFICAR_OS
  CONTROLE="/tmp/controle_conf_samba.txt"
  SAMBA_DB="/tmp/samba.db"

  # Cadastro de perguntas para cadastr o do SAMBA
  declare -A MSG_WHIP=(
    [hostanme]="Digite o HOSTNAME desejado:"
    [msg_hostname]="Exemplo srvad, dc01, srvsamba\nHostname Atual -> $(hostname):" 
    [dominio]="Digite o DOMINIO desejado:"
    [msg_dominio]="Exemplo lab.local, lab.intra:"
    [ip]="Digite o endereço IP desejado:"
    [msg_ip]="Aperte enter para usar IP atual\nIp. Atual $(hostname -I)"
    [mascara]="Digite a máscara de rede:"
    [msg_mascara]="atual -> $(ip a | grep inet | grep -v inet6 | grep -v "127.0.0.*" | awk '{print $2}' | cut -d "/" -f 2 | uniq)"
    [gateway]="Digite o gateway da rede:"
    [msg_gateway]="atual -> $(ip -o -4 route show to default | awk '{print $3}' | head -n 1):"
    [dns]="Digite o DNS EXTERNO desejado:"
    [msg_dns]="Exemplo: 8.8.8.8, 8.8.4.4:"
    [senha]="Qual a senha do admistrador do DOMINIO"
    [msg_senha]="Usar senha complexa:"
  )

  [[ -f $CONTROLE ]] && _MSG_ERRO_INFO "Script já executado, favor remover o arquivo para contiunuar $CONTROLE"

  clear 

  # Verificar se existe mais de um ip cadastrado
  CONN=$(nmcli connection show | awk '{print $4}' | grep -v -i device)
  [[ $(wc -l <<< "${CONN}") -eq 1 ]] || _MSG_ERRO_INFO 'Mais de um ip ativo, favor desativar a interface para continuar'

  #Definição e criação do banco de dados de variáveis para uso do samba4 
  echo "Samba Info" > $SAMBA_DB || _MSG_ERRO_INFO "Erro ao criar arquivo $SAMBA_DB, Favor Verificar"

  # Verificar se hostname está correto
  HOSTNAME=$(whiptail --title "${MSG_WHIP[hostname]}" --inputbox "${MSG_WHIP[msg_hostname]}" --fb 10 60 3>&1 1>&2 2>&3)
  
  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Operação cancelada'  

   # Se campo ficar em branco o nome será alterado para dc_samba
  HOSTNAME=${HOSTNAME:-dc_samba} 

  # Verificando tamanho do nome do DC
  [[ "${#HOSTNAME}" -le 15 ]] || _MSG_ERRO_INFO 'Nome do DC maior que 15 caracteres'

  # Configurar Domínio  
  DOMINIO=$(whiptail --title "${MSG_WHIP[dominio]}" --inputbox "${MSG_WHIP[msg_dominio]}" --fb 10 60 3>&1 1>&2 2>&3)
    
  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'  
  
  # Verificar se domínio possui pontos e não é menor que três caracteres
  [[ "${#DOMINIO}" -ge 3 ]] || _MSG_ERRO_INFO 'DOMINIO menor que 3 caracteres'
  [[ $(grep -cE "[.]" <<< "${DOMINIO}") -eq 0 ]] && _MSG_ERRO_INFO 'Erro ao informar dominio'

  # Obter ip em uso atualmente
  IP_ATUAL=$(hostname -I | sed 's/ //')
  IP_SAMBA=$(whiptail --title "${MSG_WHIP[ip]}" --inputbox "${MSG_WHIP[msg_ip]}" --fb 10 60 3>&1 1>&2 2>&3)
    
  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'
  IP_SAMBA=${IP_SAMBA:=$IP_ATUAL}
    
  # Verificar se ip é valido 
  which ipcalc 1> /dev/null || yum -y install ipcalc 1> /dev/null
  IPCALC=$(which ipcalc)
  "$IPCALC" -c "$IP_SAMBA" || _MSG_ERRO "$IP_ATUAL está incorreto"

  # Valor da mascara de rede atual
  MASK_ATUAL=$(ip a | grep inet | grep -v inet6 | grep -v "127.0.0.*" | awk '{print $2}' | cut -d "/" -f 2 | uniq)
  MASK=$(whiptail --title "${MSG_WHIP[mascara]}" --inputbox "${MSG_WHIP[msg_mascara]}" --fb 10 60 3>&1 1>&2 2>&3)
    
  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'
  MASK=${MASK:=$MASK_ATUAL}

  # Validando máscara de rede e ip.
  "$IPCALC" -c "$IP_SAMBA"/"$MASK" || _MSG_ERRO "IP: $IP_SAMBA/$MASK está incorreto"

  # Gateway padrao  
  GW_ATUAL=$(ip -o -4 route show to default | awk '{print $3}' | head -n 1)
  GW=$(whiptail --title "${MSG_WHIP[gateway]}" --inputbox "${MSG_WHIP[msg_gateway]}" --fb 10 60 3>&1 1>&2 2>&3)

  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'
  GW=${GW:=$GW_ATUAL}
  
  # Verificar se GW é valido
  "$IPCALC" -c "$GW" || { whiptail --title "Erro" --msgbox "GATEWAY: $GW está incorreto" 12 50 ; exit 1 ; }

  # Verificar DNS externo
  DNS=$(whiptail --title "${MSG_WHIP[dns]}" --inputbox "${MSG_WHIP[msg_dns]}" --fb 10 60 3>&1 1>&2 2>&3)
    
  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'  
  DNS=${DNS:=1.1.1.1}

  "$IPCALC" -c "$DNS" 
  ping -q -c 2 "$DNS" > /dev/null || _MSG_ERRO "DNS: $DNS está incorreto ou inacessível"

  # Informar senha do usuário administrador
  SENHA_DOM=$(whiptail --title "${MSG_WHIP[senha]}" --passwordbox "${MSG_WHIP[msg_senha]}" --fb 10 60 3>&1 1>&2 2>&3)

  # Se escolher cancelar finaliza o script
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script'

  # Caso senha for em branco assume o valor abaixo
  SENHA_DOM=${SENHA_DOM:=Senha@123}

  # Validar requisitos da senha
  # Caso a senha não atender os requisitos de complexidade, COMENTAR A LINHA ABAIXO
  _VALIDAR_SENHA "$SENHA_DOM"

  # nome da interface
  INTERFACE=$(nmcli connection show | tail -n +2 | awk '{print $4}')

  # Endereço de rede
  END_REDE=$(ip route | tail -n +2 | awk '{print $1}')

  # Verificar dados fornecidos
  whiptail --title "Dados informados pelo usuario" \
  --msgbox "
  IP........=$IP_SAMBA
  MASCARA...=$MASK
  GATEWAY...=$GW
  DNS.......=$DNS
  HOSTNAME..=$HOSTNAME
  DOMINIO...=$DOMINIO
  SENHA_DOM.=$SENHA_DOM
  REDE......=$INTERFACE
  END_REDE..=$END_REDE" --fb 30 90

  # Salvar alterações
  whiptail --title "Deseja continuar" --yesno "Os dados estao corretos SIM ou Nao." 10 50 
  [[ $? -eq 1 ]] && _MSG_SAIR 'Saindo\nFavor executar novamente o script' 

  # Configurar hostname
  hostnamectl set-hostname "$HOSTNAME" 1> /dev/null

  # Gravar arquivo para uso do samba 
  echo "IP........=${IP_SAMBA}
MASCARA...=${MASK}
GATEWAY...=${GW}
DNS.......=${DNS}
HOSTNAME..=${HOSTNAME}
DOMINIO...=${DOMINIO}
SENHA_DOM.=${SENHA_DOM}
REDE......=${INTERFACE}
END_REDE..=${END_REDE}" >> "$SAMBA_DB"

  # Adicionar arquivo de hosts
  cat >> /etc/hosts << EOF
${IP_SAMBA} ${HOSTNAME}.${DOMINIO} ${HOSTNAME}.${DOMINIO} ${HOSTNAME}
EOF

  # Obter o UUID da placa de rede
  SAMBA_UUID=$(nmcli connection show | grep -i "${INTERFACE}" | head -n 1 |rev | awk '{print $3}' | rev)

  #Here document para criar arquivo de rede
  cat > /etc/sysconfig/network-scripts/ifcfg-"${INTERFACE}" << EOF
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
UUID=
NAME=${INTERFACE}
DEVICE=${INTERFACE}
ONBOOT=yes
IPADDR=$IP_SAMBA
PREFIX=$MASK
GATEWAY=$GW
IPV6_DISABLED=yes
EOF
  # Adicionar o UUID
  sed -i "s/UUID.*/UUID=${SAMBA_UUID}/" /etc/sysconfig/network-scripts/ifcfg-"${INTERFACE}"

  # Criar arquivo de controle
  echo "Configuracao realizada, função executada foi $CONTROLE" | tee > $CONTROLE

  # Se o endereço configurado for diferente do ip atual, o servidor será reiniciado
  [[ "$IP_ATUAL" != "$IP_SAMBA" ]] && { _MSG_INFO "O Servidor vai ser reiniciado para ajuste no endereço de rede.\n\nfavor executar script novamente para continuar a instalação" ; reboot ; }
}
# Fim

################################################################################
_SAMBA_INST()
{
  _VERIFICAR_ROOT
  _VERIFICAR_OS

  CONTROLE="/tmp/controle_samba_inst.txt"
  SAMBA_DB="/tmp/samba.db"
  SAMBA_PATH="/usr/local/samba"

  [[ -f $CONTROLE ]] && _MSG_ERRO_INFO $CONTROLE
  [[ -f $SAMBA_DB ]] || _MSG_ERRO_INFO "O Arquivo $SAMBA_DB não está acessível.\nInstalação finalizada"     
    
  SAMBA_DOMIN=$(grep -i "dominio"   /tmp/samba.db | cut -d "=" -f 2 | cut -d "." -f 1)
  SAMBA_REALM=$(grep -i "dominio"   /tmp/samba.db | cut -d "=" -f 2)
  SAMBA_SENHA=$(grep -i "senha"     /tmp/samba.db | cut -d "=" -f 2)
  SAMBA_IPSRV=$(grep -i "ip"        /tmp/samba.db | cut -d "=" -f 2 | cut -d "/" -f 1)
  SAMBA_HOSTN=$(grep -i "hostname"  /tmp/samba.db | cut -d "=" -f 2)
  SAMBA_IFACE=$(grep -i "^rede"     /tmp/samba.db | cut -d "=" -f 2)

  # Testando Ip do Samba
  ping -c 2 -w 5 "$SAMBA_IPSRV" || _MSG_ERRO_INFO "O IP $SAMBA_IPSRV não está acessível.\nInstalação finalizada" 

  whiptail --title "Os dados estao corretos ?" \
  --yesno "Dominio.= [ ${SAMBA_DOMIN^^} ]\nReino...= [ ${SAMBA_REALM^^} ]\nSenha...= [ ${SAMBA_SENHA} ]" --fb 15 40
  
  [[ $? -eq 1 ]] && _MSG_SAIR "Instalação Cancelada"

  # Parametros SAMBA
  "$SAMBA_PATH"/bin/samba-tool domain provision --server-role=dc --realm="${SAMBA_REALM^^}" --domain="$SAMBA_DOMIN" --dns-backend=BIND9_DLZ --use-rfc2307 --adminpass="$SAMBA_SENHA"

  CHRONY_CONF=$(find /etc/ -type f -iname chrony.conf)

  cat >> "$CHRONY_CONF" << EOF
# Configuração adicional
log measurements statistics tracking
maxupdateskew 100.0
hwclockfile /etc/adjtime
ntpsigndsocket $SAMBA_PATH/var/lib/ntp_signd
EOF

  # Reiniciar servidor de hora
  systemctl restart chronyd 1> /dev/null

  NSSWITCH_CONF=$(find /etc/ -type f -iname nsswitch.conf)
  cp "$NSSWITCH_CONF"{,.bkp}
  sed -i 's/^passwd.*/passwd:\ files\ winbind/g' "$NSSWITCH_CONF"
  sed -i 's/^group.*/group:\ files\ winbind/g'   "$NSSWITCH_CONF"

  mkdir -p $SAMBA_PATH/var/lib/ntp_signd/ || _MSG_ERRO_INFO "Erro ao criar pasta"
  chmod 0750 $SAMBA_PATH/var/lib/ntp_signd/
  chown root.chrony $SAMBA_PATH/var/lib/ntp_signd/

  touch /var/named/data/named_mem_stats.txt || _MSG_ERRO_INFO "Erro ao arquivo named_mem_stats"
  touch /var/named/data/named_stats.txt     || _MSG_ERRO_INFO "Erro ao arquivo named_stats"
  touch /var/named/data/cache_dump.db       || _MSG_ERRO_INFO "Erro ao arquivo cache_dump"
  chown named.named /var/named -R           || _MSG_ERRO_INFO "Erro ao dar permissão para a pasta var/named"
  cp $SAMBA_PATH/bind-dns/named.conf{,.bkp}

  NAMED_VERSION=$(rpm -qa bind |cut -d "-" -f 2 |cut -d "." -f 2) || _MSG_ERRO_INFO "Versão named não encontrada"
  chown named.named $SAMBA_PATH/bind-dns/named.conf
  chown named.named $SAMBA_PATH/bind-dns -R
  chown root.named $SAMBA_PATH/lib/bind9/dlz_bind9_"$NAMED_VERSION".so
 
  cat > $SAMBA_PATH/bind-dns/named.conf  << EOF
dlz "AD DNS Zone" {
database "dlopen $SAMBA_PATH/lib/bind9/dlz_bind9_$NAMED_VERSION.so";
};
EOF

  NAMED=$(find /etc/ -iname named.conf)
  cp "$NAMED"{,.bkp}

  cat > "$NAMED" << EOF
options {
  listen-on port 53 { any; };
  listen-on-v6 port 53 { none; };
  directory "/var/named";
  dump-file "/var/named/data/cache_dump.db";
  statistics-file "/var/named/data/named_stats.txt";
  memstatistics-file "/var/named/data/named_mem_stats.txt";
  allow-query { any; };

  recursion yes;
  allow-recursion { any; };

  allow-transfer { none; };

  dnssec-enable no;
  dnssec-validation no;

  managed-keys-directory "/var/named/dynamic";
  pid-file "/run/named/named.pid";
  tkey-gssapi-keytab "/usr/local/samba/bind-dns/dns.keytab";

  forwarders {
         1.1.1.1;
         8.8.8.8;
  };

};

logging {
  channel default_debug {
    file "data/named.run";
    severity dynamic;
  };
};

zone "." IN {
  type hint;
  file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
include "$SAMBA_PATH/bind-dns/named.conf";
EOF

  echo "KRB5RCACHETYPE=\"none\"" >> /etc/sysconfig/named
  echo -e "\n[kdc]\n\tcheck-ticket-addresses = false" >> $SAMBA_PATH/private/krb5.conf

  \cp /usr/local/samba/private/krb5.conf /etc/
  cp $SAMBA_PATH/conf/smb.conf{,.bkp}

  systemctl start named && systemctl enable --now named
  sed -i '26i dns=none' /etc/NetworkManager/NetworkManager.conf

  cp /usr/lib/systemd/system/samba.service /root/samba.service.bkp
  sed -i 's/notify/forking/'  /usr/lib/systemd/system/samba.service
  sed -i 's/--.*/-D/'         /usr/lib/systemd/system/samba.service

  systemctl daemon-reload
  systemctl enable --now samba || _MSG_ERRO_INFO "Erro ao iniciar o serviço do SAMBA"
    
    #Here document para criar arquivo de dns
  chattr -i /etc/resolv.conf
  cat > /etc/resolv.conf << EOF
search $SAMBA_REALM
nameserver $SAMBA_IPSRV
EOF
  chattr +i /etc/resolv.conf

  KINIT=$(which kinit)

  sleep 1
  expect -c "
  spawn $KINIT Administrator
  expect \"Password for Administrator@${SAMBA_REALM^^}:\"
  send \"$SAMBA_SENHA\r\"
  interact"
  sleep 2
    
  SAMBA_CFSMB=$(find "${SAMBA_PATH}" -iname smb.conf)
  \cp "$SAMBA_CFSMB" /root/smb.conf.bkp

  # Configuração do arquivo smb.conf
  cat > "${SAMBA_CFSMB}" << EOF
[global]
        netbios name = ${SAMBA_HOSTN^^}
        realm = ${SAMBA_REALM^^}
        server role = active directory domain controller
        server services = s3fs, rpc, nbt, wrepl, ldap, cldap, kdc, drepl, winbindd, ntp_signd, kcc, dnsupdate
        workgroup = ${SAMBA_DOMIN^^}
        idmap_ldb:use rfc2307 = yes
        interfaces=lo ${SAMBA_IFACE}
        bind interfaces only = yes
        template shell = /bin/bash
        template homedir = /home/%U
        winbind enum users = yes
        winbind enum groups = yes
        winbind use default domain = yes
        ntlm auth = yes
        ldap server require strong auth = no
        winbind nss info = rfc2307
        vfs objects = acl_xattr, recycle, dfs_samba4
        map acl inherit = Yes
        store dos attributes = Yes

[sysvol]
        path = $SAMBA_PATH/var/locks/sysvol
        read only = No

[netlogon]
        path = $SAMBA_PATH/var/locks/sysvol/${SAMBA_REALM,,}/scripts
        read only = No
EOF

    # Ajustar conforme o ambiente
  SAMBA_TOOL=$(find /usr/ -iname samba-tool)
  "$SAMBA_TOOL" domain passwordsettings set --complexity=off    > /dev/null 2>&1
  "$SAMBA_TOOL" domain passwordsettings set --history-length=0  > /dev/null 2>&1
  "$SAMBA_TOOL" domain passwordsettings set --min-pwd-age=0     > /dev/null 2>&1
  "$SAMBA_TOOL" domain passwordsettings set --min-pwd-length=3  > /dev/null 2>&1
  "$SAMBA_TOOL" domain passwordsettings set --max-pwd-age=0     > /dev/null 2>&1

  whiptail --title "Politica de senha" --msgbox "$($SAMBA_PATH/bin/samba-tool domain passwordsettings show)" --fb 20 50  

  "$SAMBA_PATH"/bin/net rpc rights grant "${SAMBA_DOMIN^^}\Domain Admins" SeDiskOperatorPrivilege -U"${SAMBA_DOMIN^^}\administrator%$SAMBA_SENHA"
  "$SAMBA_PATH"/bin/net rpc rights list accounts -U"${SAMBA_DOMIN^^}\administrator%${SAMBA_SENHA}"
  "$SAMBA_PATH"/bin/smbcontrol all reload-config

  IP_REVERSO=$(_REVERSO)
  "$SAMBA_TOOL" dns zonecreate "${SAMBA_HOSTN}" "${IP_REVERSO}" -UAdministrator%"${SAMBA_SENHA}"
  "$SAMBA_TOOL" dns add "${SAMBA_HOSTN}" "${IP_REVERSO}" "${SAMBA_IPSRV##*.}" PTR "${SAMBA_HOSTN}.${SAMBA_REALM}" -UAdministrator%"${SAMBA_SENHA}"

  # Deletar registros ipv6 da pesquisa, se utilizar ipv6 remover as 2 linhas abaixo
  \cp /var/named/named.ca /root/
  sed -i '/AAAA/d' /var/named/named.ca

  $SAMBA_PATH/sbin/samba_dnsupdate
  systemctl restart samba.service 1> /dev/null
  systemctl restart named.service 1> /dev/null

  sed -i '8i After=samba.service' /lib/systemd/system/named.service 1> /dev/null
  systemctl daemon-reload 1> /dev/null

  echo "Configuracao realizada, função executada foi _CONF_SAMBA" | tee > $CONTROLE

  # Realizar testes
  clear
  SMB_KLIST=$(klist) 1> /dev/null
  SMB_VERSAO="$(smbclient --version)"                         1> /dev/null
  SMB_HOST=$(host -t A "$SAMBA_REALM")                        1> /dev/null
  SMB_SHARE=$(smbclient -L localhost -U%)                     1> /dev/null
  SMB_LDAP=$(host -t SRV _ldap._tcp."$SAMBA_REALM")           1> /dev/null
  SMB_KERBEROS=$(host -t SRV _kerberos._udp."$SAMBA_REALM".)  1> /dev/null

  # Exibir informações
  whiptail --title "Informações" --msgbox \
   "\n[Versão...:] $SMB_VERSAO 
    \n[Share....:] $SMB_SHARE
    \n[Host.....:] $SMB_HOST
    \n[Ldap.....:] $SMB_LDAP
    \n[Kerberos.:] $SMB_KERBEROS
    \n[klist....:] $SMB_KLIST " --fb 30 100


  if whiptail --title "Aplicar Configurações - SAMBA $(smbclient --version | awk '{print$2}')" --yesno "Deseja reiniciar o servidor" 10 50 ; then reboot ; fi 
}
# Fim

################################################################################
_SAMBA_CHECK()
{
  clear
  # Verificar se o samba está em execução
  systemctl status samba.service | grep -iq active || _MSG_ERRO_INFO "Samba não instalado ou serviço não está em execução"
  
  # Carregar informações
  SAMBA_DB="/tmp/samba.db"
  [[ -f $SAMBA_DB ]] || _MSG_ERRO_INFO "O Arquivo $SAMBA_DB não está acessível.\nInstalação finalizada" 
  
  MSG_TESTE="
  Será realizado as seguintes operações:

  Verificação e correção banco de dados.....-> (dbcheck)
  Verificação e correção volume do systema..-> (sysvol)
  Atualização dos registros de dns..........-> (samba_dns)
  Recarregar as configurações do SAMBA......-> (reload)"

  if ! whiptail --title "Validar recursos SAMBA $(smbclient --version | awk '{print$2}')" --yesno "$MSG_TESTE" 20 65 ; then exit 20 ; fi 

  SAMBA_TOOL=$(find /usr -iname samba-tool)
  "$SAMBA_TOOL" domain info "$(hostname)" > /tmp/samba_dc_info
  
  SAMBA_DOM=$(grep -i ^domain /tmp/samba_dc_info | awk '{print $3}')
  DNS_UPDATE=$(find /usr -iname samba_dnsupdate)
  SMBCONTROL=$(find /usr -iname smbcontrol)
  SAMBA_SENHA=$(grep -i "senha"     /tmp/samba.db | cut -d "=" -f 2)


  clear
  "$SAMBA_TOOL" dbcheck                                             && { sleep 2; echo -e "\nVerificando" ; }
  "$SAMBA_TOOL" dbcheck --cross-ncs                                 && { sleep 2; echo -e "\nVerificando" ; }
  "$SAMBA_TOOL" dbcheck --cross-ncs --fix --yes                     && { sleep 2; echo -e "\nVerificando" ; }
  "$SAMBA_TOOL" dbcheck --cross-ncs --reset-well-known-acls --fix   && { sleep 2; echo -e "\nVerificando" ; }
  "$SAMBA_TOOL" ntacl sysvolcheck                                   && { sleep 2; echo -e "\nVerificando" ; }
  "$SAMBA_TOOL" ntacl sysvolreset                                   && { sleep 2; echo -e "\nVerificando" ; }

  clear
  wbinfo --ping-dc                          && { sleep 2; echo -e "\nVerificando" ; }
  getent passwd Administrator               && { sleep 2; echo -e "\nVerificando" ; }
  host -t SRV _ldap._tcp."$SAMBA_DOM".      && { sleep 2; echo -e "\nVerificando" ; }
  host -t SRV _kerberos._udp."$SAMBA_DOM".  && { sleep 2; echo -e "\nVerificando" ; }
  host -t A "$(hostname)"."$SAMBA_DOM".     && { sleep 2; echo -e "\nVerificando" ; }
  wbinfo --ping-dc                          && { sleep 2; echo -e "\nVerificando" ; }
  samba-tool dns query "$(hostname)" "$SAMBA_DOM" @ ALL -UAdministrator%"${SAMBA_SENHA}"  && { sleep 2; echo -e "\nVerificando" ; }
  host -t SRV _ldap._tcp.Default-First-Site-Name._sites.ForestDnsZones."$SAMBA_DOM".      && { sleep 2; echo -e "\nVerificando" ; }
  
  clear
  "$DNS_UPDATE" --verbose         && { sleep 2; echo -e "\nVerificando" ; } && { sleep 2; echo -e "Atualizando\n" ; }
  "$SMBCONTROL" all reload-config && { sleep 2; echo -e "\nVerificando" ; } && { sleep 2; echo -e "Recarregando\n" ; }
  

}
# Fim declaração de função



#############################################################################################################################
#                                                 Inicio do script                                                          #
#############################################################################################################################

_Menu() {
    SEL=$(whiptail --title "Menu" --fb --menu "Escolha uma opção" 15 60 6 \
        "1" "Instalar Samba "           \
        "2" "Baixar pacotes e compilar" \
        "3" "Configurar"                \
        "4" "Instalar"                  \
        "5" "Realizar Teste do Samba"   \
        "9" "Sair" 3>&1 1>&2 2>&3)
    case $SEL in
        1)
            echo "Escolhida 1"
            _CONFIGURAR
            _CONF_SAMBA
            _SAMBA_INST
        ;;
        2)
            echo "Escolhida 2"
            _CONFIGURAR
        ;;
        3)
            echo "Escolhida 3"
           _CONF_SAMBA
        ;;
        4)
            echo "Escolhida 4"
           _SAMBA_INST
        ;;
        5)
            echo "Escolhida 4"
           _SAMBA_CHECK
        ;;
        9)
            echo "Escolhida 5"
            exit
        ;;
    esac
}
_Menu


#_CONFIGURAR
#_CONF_SAMBA
#_SAMBA_INST


# Extra criar compartilhamento

# chown root:"Domain Admins" /srv/samba/Demo/
# chmod 0770 /srv/samba/Demo/

#Add the [Demo] share definition to your smb.conf file:

#[Demo]
#       path = /srv/samba/Demo/
#       read only = no



